global:
 scrape_interval: 10s
scrape_configs:
 - job_name: 'prometheus_metrics'
   scrape_interval: 5s
   static_configs:
     - targets: ['54.185.14.223:9090']
 - job_name: 'node_exporter_metrics'
   scrape_interval: 5s
   static_configs:
    - targets: ['54.185.14.223:9100','34.218.238.52:9100']
